version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Python development dependencies
  - package-ecosystem: "pip"
    directories:
      - "/"
      - "/client"
      - "/export"
      - "/log"
      - "/proxy"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "development"
    ignore:
      - dependency-name: "pyqt*"
