version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Python development dependencies
  - package-ecosystem: "pip"
    directory: "/client"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "development"
    groups:
      dev-dependencies:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directory: "/export"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "development"
    groups:
      dev-dependencies:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directory: "/log"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "development"
    groups:
      dev-dependencies:
        patterns: ["*"]
  - package-ecosystem: "pip"
    directory: "/proxy"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "development"
    groups:
      dev-dependencies:
        patterns: ["*"]
