version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout

      - run:
          name: Install requirements and run tests
          command: |
            virtualenv .venv
            source .venv/bin/activate
            pip install --require-hashes -r dev-requirements.txt
            make test

      - run:
          name: Check Python dependencies for CVEs
          command: |
            set -e
            source .venv/bin/activate
            make safety
