---
common-steps:
  - &client_install_poetry
    run:
      name: Install Poetry
      command: |
        set -e
        source /etc/os-release
        if [[ "$VERSION_CODENAME" == "bullseye" ]]; then
            # Install Poetry via PyPI
            apt-get update && apt-get install --yes --no-install-recommends python3-pip
            pip install poetry==1.6.1
        elif [[ "$VERSION_CODENAME" == "bookworm" ]]; then
            # Install Poetry via system package
            apt-get update && apt-get install --yes --no-install-recommends python3-poetry
        else
            echo "Unsupported Debian version: $VERSION_CODENAME"
            exit 1
        fi

  - &client_install_testing_dependencies
    run:
      name: Install testing dependencies
      command: |
        set -e
        apt update && apt install -y git gnupg libarchive13 libmagic1 libqt5x11extras5 make python3-tk python3-dev gnupg python3-venv sqlite3 xvfb
        cd client
        poetry install --no-ansi

  - &client_configure_locales
    run:
      name: Configure locales
      command: |
        set -e
        apt update && apt install -y locales
        echo "en_US ISO-8859-1" >> /etc/locale.gen
        echo "en_US UTF-8" >> /etc/locale.gen
        locale-gen

  - &client_run_unit_tests
    run:
      name: Install requirements and run unit tests
      command: |
        set -e
        cd client
        export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
        make test-random

  - &client_run_integration_tests
    run:
      name: Install requirements and run integration tests
      command: |
        set -e
        cd client
        export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
        make test-integration

  - &client_run_functional_tests
    run:
      name: Install requirements and run functional tests
      command: |
        set -e
        cd client
        export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
        make test-functional

  - &client_run_lint
    run:
      name: Run lint, type checking, code formatting
      command: |
        set -e
        make -C client check-black check-isort lint mypy

  - &client_check_security
    run:
      name: Run static analysis on source code to find security issues
      command: |
        set -e
        make -C client semgrep bandit

  - &client_check_source_strings
    run:
      name: Check that source strings are updated
      command: |
        set -e
        make -C client check-strings

  - &client_check_mo_repro
    run:
      name: Check that translation machine objects are reproducible
      command: |
        set -e
        make -C client verify-mo

  - &client_check_python_dependencies_for_vulnerabilities
    run:
      name: Check Python dependencies for known vulnerabilities
      command: |
        set -e
        make -C client safety

  - &export_install_poetry
    run:
      name: Install Poetry
      command: |
        set -e
        source /etc/os-release
        if [[ "$VERSION_CODENAME" == "bullseye" ]]; then
            # Install Poetry via PyPI
            apt-get update && apt-get install --yes --no-install-recommends python3-pip
            pip install poetry==1.6.1
        elif [[ "$VERSION_CODENAME" == "bookworm" ]]; then
            # Install Poetry via system package
            apt-get update && apt-get install --yes --no-install-recommends python3-poetry
        else
            echo "Unsupported Debian version: $VERSION_CODENAME"
            exit 1
        fi

  - &export_install_testing_dependencies
    run:
      name: Install testing dependencies
      command: |
        apt update && apt install -y git gnupg make python3-dev gnupg python3-venv libnotify-bin
        cd export
        poetry install --no-ansi

  - &export_run_unit_tests
    run:
      name: Install requirements and run unit tests
      command: |
        cd export
        export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
        make test

  - &export_run_lint
    run:
      name: Run lint, type checking, code formatting
      command: |
        make -C export check-black lint

  - &export_check_security
    run:
      name: Run static analysis on source code to find security issues
      command: |
        make -C export semgrep

  - &export_check_python_dependencies_for_vulnerabilities
    run:
      name: Check Python dependencies for known vulnerabilities
      command: |
        make -C export safety

  - &log_install_poetry
    run:
      name: Install Poetry
      command: |
        set -e
        source /etc/os-release
        if [[ "$VERSION_CODENAME" == "bullseye" ]]; then
            # Install Poetry via PyPI
            apt-get update && apt-get install --yes --no-install-recommends python3-pip
            pip install poetry==1.6.1
        elif [[ "$VERSION_CODENAME" == "bookworm" ]]; then
            # Install Poetry via system package
            apt-get update && apt-get install --yes --no-install-recommends python3-poetry
        else
            echo "Unsupported Debian version: $VERSION_CODENAME"
            exit 1
        fi

  - &log_install_testing_dependencies
    run:
      name: Install testing dependencies
      command: |
        apt-get install --yes --no-install-recommends git gnupg make
        cd log
        poetry install --no-ansi

  - &log_run_tests
    run:
      name: Install requirements and run tests
      command: |
        make -C log check

  - &proxy_install_poetry
    run:
      name: Install Poetry
      command: |
        set -e
        source /etc/os-release
        if [[ "$VERSION_CODENAME" == "bullseye" ]]; then
            # Install Poetry via PyPI
            apt-get update && apt-get install --yes --no-install-recommends python3-pip
            pip install poetry==1.6.1
        elif [[ "$VERSION_CODENAME" == "bookworm" ]]; then
            # Install Poetry via system package
            apt-get update && apt-get install --yes --no-install-recommends python3-poetry
        else
            echo "Unsupported Debian version: $VERSION_CODENAME"
            exit 1
        fi

  - &proxy_install_testing_dependencies
    run:
      name: Install testing dependencies
      command: |
        apt-get install --yes --no-install-recommends git gnupg make
        cd proxy
        poetry install --no-ansi

  - &proxy_run_unit_tests
    run:
      name: Install requirements and run unit tests
      command: |
        cd proxy
        export PYTHONPATH=$PYTHONPATH:.  # so alembic can get to Base metadata
        make test

  - &proxy_run_lint
    run:
      name: Run lint, type checking, code formatting
      command: |
        make -C proxy lint

  - &proxy_check_security
    run:
      name: Run static analysis on source code to find security issues
      command: |
        set -e
        cd proxy
        poetry update bandit
        make bandit

  - &proxy_check_python_dependencies_for_vulnerabilities
    run:
      name: Check Python dependencies for known vulnerabilities
      command: |
        set -e
        cd proxy
        poetry update safety
        make safety

version: 2.1

jobs:
  client_unit-test:
    parameters: &parameters
      image:
        type: string
    docker: &docker
      - image: debian:<< parameters.image >>
    steps:
      - *client_install_poetry
      - checkout
      - *client_install_testing_dependencies
      - *client_configure_locales
      - *client_run_unit_tests
      - store_test_results:
          path: test-results

  client_integration-test:
    parameters: *parameters
    docker: *docker
    steps:
      - *client_install_poetry
      - checkout
      - *client_install_testing_dependencies
      - *client_run_integration_tests

  client_functional-test:
    parameters: *parameters
    docker: *docker
    steps:
      - *client_install_poetry
      - checkout
      - *client_install_testing_dependencies
      - *client_run_functional_tests

  client_lint:
    parameters: *parameters
    docker: *docker
    steps:
      - *client_install_poetry
      - checkout
      - *client_install_testing_dependencies
      - *client_run_lint

  client_check-security:
    parameters: *parameters
    docker: *docker
    steps:
      - *client_install_poetry
      - checkout
      - *client_install_testing_dependencies
      - *client_check_security

  client_check-python-security:
    parameters: *parameters
    docker: *docker
    steps:
      - *client_install_poetry
      - checkout
      - *client_install_testing_dependencies
      - *client_check_python_dependencies_for_vulnerabilities


  client_check-internationalization:
    parameters: *parameters
    docker: *docker
    steps:
      - *client_install_poetry
      - checkout
      - *client_install_testing_dependencies
      - *client_check_source_strings
      - *client_check_mo_repro

  export_unit-test:
    parameters: *parameters
    docker: *docker
    steps:
      - *export_install_poetry
      - checkout
      - *export_install_testing_dependencies
      - *export_run_unit_tests
      - store_test_results:
          path: test-results

  export_lint:
    parameters: *parameters
    docker: *docker
    steps:
      - *export_install_poetry
      - checkout
      - *export_install_testing_dependencies
      - *export_run_lint

  export_check-security:
    parameters: *parameters
    docker: *docker
    steps:
      - *export_install_poetry
      - checkout
      - *export_install_testing_dependencies
      - *export_check_security

  export_check-python-security:
    parameters: *parameters
    docker: *docker
    steps:
      - *export_install_poetry
      - checkout
      - *export_install_testing_dependencies
      - *export_check_python_dependencies_for_vulnerabilities

  log_test-bullseye:
    docker:
      - image: debian:bullseye
    steps:
      - checkout
      - *log_install_poetry
      - *log_install_testing_dependencies
      - *log_run_tests

  proxy_unit-test:
    parameters: *parameters
    docker: *docker
    steps:
      - checkout
      - *proxy_install_poetry
      - *proxy_install_testing_dependencies
      - *proxy_run_unit_tests
      - store_test_results:
          path: test-results

  proxy_lint:
    parameters: *parameters
    docker: *docker
    steps:
      - checkout
      - *proxy_install_poetry
      - *proxy_install_testing_dependencies
      - *proxy_run_lint

  proxy_check-security:
    parameters: *parameters
    docker: *docker
    steps:
      - checkout
      - *proxy_install_poetry
      - *proxy_install_testing_dependencies
      - *proxy_check_security

  proxy_check-python-security:
    parameters: *parameters
    docker: *docker
    steps:
      - checkout
      - *proxy_install_poetry
      - *proxy_install_testing_dependencies
      - *proxy_check_python_dependencies_for_vulnerabilities


workflows:
  securedrop_client_ci:
    jobs: &client_jobs
      - client_unit-test:
          matrix: &matrix
            parameters:
              image:
                - bullseye
                - bookworm
      - client_integration-test:
          matrix: *matrix
      - client_functional-test:
          matrix: *matrix
      - client_lint:
          matrix: *matrix
      - client_check-security:
          matrix: *matrix
      - client_check-python-security:
          matrix: *matrix
      - client_check-internationalization:
          matrix: *matrix

  securedrop_export_ci:
    jobs: &export_jobs
      - export_unit-test:
          matrix: *matrix
      - export_lint:
          matrix: *matrix
      - export_check-security:
          matrix: *matrix
      - export_check-python-security:
          matrix: *matrix

  securedrop_log_ci:
    jobs:
      - log_test-bullseye

  securedrop_proxy_ci:
    jobs: &proxy_jobs
      - proxy_unit-test:
          matrix: *matrix
      - proxy_lint:
          matrix: *matrix
      - proxy_check-security:
          matrix: *matrix
      - proxy_check-python-security:
          matrix: *matrix

  client_nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
    jobs: *client_jobs

  export_nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
    jobs: *export_jobs

  proxy_nightly:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - main
    jobs: *proxy_jobs
