version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.7-buster
    steps:
      - checkout
      - run:
          name: Run tests
          command: python3 -m unittest

workflows:
  version: 2
  per_pr:
    jobs:
      - test
